### ISSUE TITLE
Pulse Shader in constant updated Mesh generated from point cloud is not transparent?

### ISSUE THREAD

**Issue by masterchop** [keijiro/Doodle#1]
I was testing this effects which is very very cool as pretty much everything you do. But when i apply this type of shaders To a point cloud that updates a mesh on every frame the effect is not transparent, so the pulse effect is lost. I have the same behavior of this video: https://www.youtube.com/watch?v=xQHeFvQ_1z8 is just a different shader but the problem is the same.  Is there any way i can avoid the gray area? that is the albedo color applied on the shader.

**Comment by keijiro** [comment]
Let me summarize the points.

- You can apply the pulse shader to any type of mesh, even if it's generated from a dynamic point cloud.
- The pulse shader is opaque (i.e. not transparent) because I only need opaque effect.
- The shader has to be rewritten to make it transparent.

This repository was made for experimental purposes. I have no plan for rewriting the shader at the moment.

I'm closing this issue. Please feel free to reopen if you have further issues.

**Comment by masterchop** [comment]
thank you for checking out
